version: "3.8"

services:
  db:
    image: library/postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - db
    restart: "on-failure"


volumes:
  postgres_data:
  static_volume:
