# Generated by Django 3.2 on 2021-04-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='dish',
            field=models.ManyToManyField(blank=True, related_name='menu', to='menu.Dish'),
        ),
    ]
